version: '3'


services:
  postgres_app:
    image: postgres
    volumes:
      - /home/valia/Desktop/Thesis/volumes/postgrs/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  postgres_keycloak:
    image: postgres
    volumes:
      - /home/valia/Desktop/Thesis/volumes/postgres_keycloak/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL: jdbc:postgresql://postgres_keycloak/keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - 8081:8080
    depends_on:
      - postgres_keycloak